from http import HTTPStatus
from typing import Any, Optional, Union, cast

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.bad_request_error_response import BadRequestErrorResponse
from ...models.generative_answers_feedback_request import GenerativeAnswersFeedbackRequest
from ...models.generative_answers_feedback_response_403 import GenerativeAnswersFeedbackResponse403
from ...types import Response


def _get_kwargs(
    *,
    body: GenerativeAnswersFeedbackRequest,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/hc/api/internal/generative_answers_feedback",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Optional[Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]]:
    if response.status_code == 204:
        response_204 = cast(Any, None)
        return response_204

    if response.status_code == 400:
        response_400 = BadRequestErrorResponse.from_dict(response.json())

        return response_400

    if response.status_code == 403:
        response_403 = GenerativeAnswersFeedbackResponse403.from_dict(response.json())

        return response_403

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Response[Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: Union[AuthenticatedClient, Client],
    body: GenerativeAnswersFeedbackRequest,
) -> Response[Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]]:
    """Submits feedback for a generated answer

     Submits feedback for a generated answer. This feedback can be used to improve the quality of future
    answers generated by the system.

    Args:
        body (GenerativeAnswersFeedbackRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: Union[AuthenticatedClient, Client],
    body: GenerativeAnswersFeedbackRequest,
) -> Optional[Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]]:
    """Submits feedback for a generated answer

     Submits feedback for a generated answer. This feedback can be used to improve the quality of future
    answers generated by the system.

    Args:
        body (GenerativeAnswersFeedbackRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: Union[AuthenticatedClient, Client],
    body: GenerativeAnswersFeedbackRequest,
) -> Response[Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]]:
    """Submits feedback for a generated answer

     Submits feedback for a generated answer. This feedback can be used to improve the quality of future
    answers generated by the system.

    Args:
        body (GenerativeAnswersFeedbackRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: Union[AuthenticatedClient, Client],
    body: GenerativeAnswersFeedbackRequest,
) -> Optional[Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]]:
    """Submits feedback for a generated answer

     Submits feedback for a generated answer. This feedback can be used to improve the quality of future
    answers generated by the system.

    Args:
        body (GenerativeAnswersFeedbackRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[Any, BadRequestErrorResponse, GenerativeAnswersFeedbackResponse403]
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
